# Argo CD Application for Cluster 1
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-cluster1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/binod132/argo'
    targetRevision: main
    path: test
  destination:
    server: 'https://10.0.2.4:6443'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
# Argo CD Application for Cluster 2
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-cluster2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/binod132/argo'
    targetRevision: main
    path: test
  destination:
    server: 'https://10.0.2.5:6443'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
